"""
services/user_query.py — Backward-compatibility aliases for services.identity.

All database queries and domain logic for users, accounts, and member identities
have been consolidated into ``app.services.identity``. This module re-exports all
public and internal symbols so existing callers and test fixtures continue to work.
"""
from __future__ import annotations

from .identity import (
    AccountState,
    AmbiguousGoogleEmailError,
    LEGACY_NAME_MARKER,
    PASSWORD_RESET_MARKER,
    _available_google_username,
    _count_users,
    _find_by_username,
    _get_or_create_profile,
    _is_admin_username,
    _profile_payload,
    _strip_internal_display_markers,
    consume_password_reset_token,
    count_users,
    create_password_reset_token,
    create_user,
    delete_user,
    encode_display_name,
    find_user_by_id,
    find_user_by_username,
    find_user_by_username_and_email,
    get_member_profile,
    is_db_enabled,
    list_users,
    parse_account_state,
    resolve_google_identity,
    revoke_password_reset_token,
    session_scope,
    set_last_login,
    update_member_profile,
    update_user_by_admin,
    update_user_profile,
)

__all__ = [
    "AccountState",
    "AmbiguousGoogleEmailError",
    "LEGACY_NAME_MARKER",
    "PASSWORD_RESET_MARKER",
    "_available_google_username",
    "_count_users",
    "_find_by_username",
    "_get_or_create_profile",
    "_is_admin_username",
    "_profile_payload",
    "_strip_internal_display_markers",
    "consume_password_reset_token",
    "count_users",
    "create_password_reset_token",
    "create_user",
    "delete_user",
    "encode_display_name",
    "find_user_by_id",
    "find_user_by_username",
    "find_user_by_username_and_email",
    "get_member_profile",
    "is_db_enabled",
    "list_users",
    "parse_account_state",
    "resolve_google_identity",
    "revoke_password_reset_token",
    "session_scope",
    "set_last_login",
    "update_member_profile",
    "update_user_by_admin",
    "update_user_profile",
]
